repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      args: [--line-length=100]
      language_version: python3.7
  - repo: git://github.com/pre-commit/mirrors-mypy
    rev: v0.761
    hooks:
    - id: mypy
  - repo: git://github.com/alphagov/verify-travis-pre-commit-hook
    sha: master
    hooks:
    - id: travis-yml-lint
  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.1.0
    hooks:
    -   id: seed-isort-config
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
    -   id: isort
  - repo: https://github.com/Agilicus/pre-commit-hook-k8svalidate.git
    rev: v0.0.6
    hooks:
      - id: k8svalidate
        args: [--exclude, '**/*.patch.yaml']
        files: .yaml$
