repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      args: [--line-length=100]
      language_version: python3.9
  - repo: git://github.com/pre-commit/mirrors-mypy
    rev: v0.780
    hooks:
    - id: mypy
  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.1.0
    hooks:
    -   id: seed-isort-config
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
    -   id: isort
  - repo: https://github.com/petalmd/dockerfile-pre-commit
    rev: v1.0
    hooks:
    - id: dockerlint
