apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: minikube-ingress
  annotations:
spec:
  rules:
  - host: sparkkubernetes
    http:
      paths:
      - path: /
        backend:
          serviceName: sparkmaster
          servicePort: 8080
